# ..######..########.########.....###....########..##.....##.####.##.....##
# .##....##.##.......##.....##...##.##...##.....##.##.....##..##..###...###
# .##.......##.......##.....##..##...##..##.....##.##.....##..##..####.####
# ..######..######...########..##.....##.########..#########..##..##.###.##
# .......##.##.......##...##...#########.##........##.....##..##..##.....##
# .##....##.##.......##....##..##.....##.##........##.....##..##..##.....##
# ..######..########.##.....##.##.....##.##........##.....##.####.##.....##
# ─────────────────────────────────────────────────────────────────────────
#  Seraphim – Hyprland Rice
#  by 90S31D0N
#  Arch Linux | Monochrome | Minimal Setup
# ─────────────────────────────────────────────────────────────────────────

###################
### KEYBINDINGS ###
###################

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, SPACE, exec, $menu
bind = $mainMod, B, exec, $browser
bind = ,XF86SelectiveScreenshot, exec, hyprshot -m region --raw | satty --filename -
bind = , Print, exec, hyprshot -m window
bind = $mainMod, Print, exec, hyprshot -m output
bind = ,XF86Favorites, exec, hyprpicker -a
bind = ,XF86Calculator, exec, $calculator
bind = $mainMod SHIFT, E, exec, rofimoji --action copy

bind = $mainMod SHIFT, B, exec, ~/.config/hypr/scripts/restart-bar.sh
bind = $mainMod SHIFT, W, exec, ~/.config/hypr/scripts/wallpaper-picker.sh
bind = $mainMod SHIFT, A, exec, ~/.config/hypr/scripts/rofi-audio.sh 

bind = $mainMod, O, exec, ~/.config/hypr/scripts/toggle-minipin.sh

# bind = $mainMod, v, exec, ~/.config/rofi/clipboard.sh


bind = SUPER, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy


bind  = SUPER_SHIFT, code:201, exec, $ai

# bind = , KP_End, exec, wtype -k right
# bind = , KP_Insert, exec, wtype " 0,

bind = SUPER ALT, T, exec, wtype "Hallo Welt" & notify-send "Test"
