# ..######..########.########.....###....########..##.....##.####.##.....##
# .##....##.##.......##.....##...##.##...##.....##.##.....##..##..###...###
# .##.......##.......##.....##..##...##..##.....##.##.....##..##..####.####
# ..######..######...########..##.....##.########..#########..##..##.###.##
# .......##.##.......##...##...#########.##........##.....##..##..##.....##
# .##....##.##.......##....##..##.....##.##........##.....##..##..##.....##
# ..######..########.##.....##.##.....##.##........##.....##.####.##.....##
# ─────────────────────────────────────────────────────────────────────────
#  Seraphim – Hyprland Rice
#  by 90S31D0N
#  Arch Linux | Monochrome | Minimal Setup
# ─────────────────────────────────────────────────────────────────────────

#################
### AUTOSTART ###
#################
exec-once = hypridle
# exec-once = waybar & waybar -c ~/.config/waybar/external.jsonc &
exec-once = qs -p ~/.config/testshell/03-example-bar.qml
exec-once = elephant
exec-once = walker --gapplication-service
# exec-once = hyprpaper
# Autostart swww
exec-once = awww-daemon

# ─── Autostart ─────────────────────────────────────────
# 1x Terminal mit Spezial-Titel -> landet im special:term
#exec-once = kitty --title SPECIAL_TERM          # kitty
exec-once = [workspace special:term silent] alacritty --title SPECIAL_TERM &   # alacritty (Alternative)
# exec-once = wezterm start --title SPECIAL_TERM  # wezterm (Alternative)

# Spotify & WhatsApp (PWA-Beispiel mit Brave)
#exec-once = [workspace special:spotify silent] spotify-launcher &
#exec-once = [workspace special:whatsapp silent] gtk-launch 'WhatsApp' &


exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

exec-once = solaar --window=hide

exec-once = 

exec-once = protonmail-bridge --no-window
