# ..######..########.########.....###....########..##.....##.####.##.....##
# .##....##.##.......##.....##...##.##...##.....##.##.....##..##..###...###
# .##.......##.......##.....##..##...##..##.....##.##.....##..##..####.####
# ..######..######...########..##.....##.########..#########..##..##.###.##
# .......##.##.......##...##...#########.##........##.....##..##..##.....##
# .##....##.##.......##....##..##.....##.##........##.....##..##..##.....##
# ..######..########.##.....##.##.....##.##........##.....##.####.##.....##
# ─────────────────────────────────────────────────────────────────────────
#  Seraphim – Hyprland Rice
#  by 90S31D0N
#  Arch Linux | Monochrome | Minimal Setup
# ─────────────────────────────────────────────────────────────────────────

###################
### MY PROGRAMS ###
###################

$terminal = alacritty
$fileManager = nautilus
$browser = librewolf
$menu = rofi -show drun
$mainMod = SUPER
$calculator = gnome-calculator
$ai = ~/.config/hypr/scripts/menu_ai.sh

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
# env = GTK_THEME, Adwaita-dark

source=~/.config/hypr/macchiato.conf

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/variables.conf
source = ~/.config/hypr/permissions.conf
source = ~/.config/hypr/look.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/windows.conf
source = ~/.config/hypr/workspaces.conf

source = ~/.config/hypr/keybinds/media.conf
source = ~/.config/hypr/keybinds/navigation.conf
source = ~/.config/hypr/keybinds/utils.conf

windowrule {
    name = "Smile"
    match:class = it.mijorus.smile
    float = on
    center = on
    pin = on
    size = 600 400
}