# ..######..########.########.....###....########..##.....##.####.##.....##
# .##....##.##.......##.....##...##.##...##.....##.##.....##..##..###...###
# .##.......##.......##.....##..##...##..##.....##.##.....##..##..####.####
# ..######..######...########..##.....##.########..#########..##..##.###.##
# .......##.##.......##...##...#########.##........##.....##..##..##.....##
# .##....##.##.......##....##..##.....##.##........##.....##..##..##.....##
# ..######..########.##.....##.##.....##.##........##.....##.####.##.....##
# ─────────────────────────────────────────────────────────────────────────
#  Seraphim – Hyprland Rice
#  by 90S31D0N
#  Arch Linux | Monochrome | Minimal Setup
# ─────────────────────────────────────────────────────────────────────────

#############
### INPUT ###
#############

input {
    kb_layout = ch 
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    kb_options = caps:swapescape
    kb_options = KP_End:" 1,"
    kb_options = 276:SUPER

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace
gesture = 3, up, special, spotify
gesture = 3, down, special, whatsapp


device {
    name = gxtp7936:00-27c6:0123
    output = eDP-1
}

device {
    name = wch.cn-touchscreen-1
    output = DP-1
}
