# ..######..########.########.....###....########..##.....##.####.##.....##
# .##....##.##.......##.....##...##.##...##.....##.##.....##..##..###...###
# .##.......##.......##.....##..##...##..##.....##.##.....##..##..####.####
# ..######..######...########..##.....##.########..#########..##..##.###.##
# .......##.##.......##...##...#########.##........##.....##..##..##.....##
# .##....##.##.......##....##..##.....##.##........##.....##..##..##.....##
# ..######..########.##.....##.##.....##.##........##.....##.####.##.....##
# ─────────────────────────────────────────────────────────────────────────
#  Seraphim – Hyprland Rice
#  by 90S31D0N
#  Arch Linux | Monochrome | Minimal Setup
# ─────────────────────────────────────────────────────────────────────────

###############
### WINDOWS ###
###############

# windowrule = suppressevent maximize, class:.*

windowrule = opacity 0.95, match:class Alacritty
windowrule = opacity 0.95, match:class codium
# windowrule = opacity 0.95, match:class zen

# ─── Special Workspaces ──────────────────────────────

# # Spotify
# windowrulev2 = workspace special:spotify, class:^(Spotify)$

# # WhatsApp (PWA in z. B. Brave oder Chromium)
# windowrulev2 = workspace special:whatsapp, class:^(chrome-web.whatsapp.com__-Default)$

# windowrulev2 = workspace special:term, title:^(SPECIAL_TERM)$, class:^(Alacritty)$

# windowrulev2 = noinitialfocus, class:^(Spotify)$
# windowrulev2 = noinitialfocus, class:^(chrome-web.whatsapp.com__-Default)$
# windowrulev2 = noinitialfocus, title:^(SPECIAL_TERM)$, class:^(Alacritty)$

# windowrulev2 = float, class:ch-fhnw-prog1-polymorphisminterfaces-swissmap-SwissMapApp

# windowrulev2 = float, class:^(libreoffice-impress)$
# windowrulev2 = center, class:^(libreoffice-impress)$



# layerrule = blur, quickshell
# layerrule = ignorezero, quickshell
# layerrule = ignorealpha [0.12], quickshell
# layerrule = ignorezero, waybar

##### Open Files Rules #####
windowrule = match:title Open Files, float on, center on, size 800 600

windowrule {
    name = "Satty"
    match:title = satty
    float = on
    center = on
    size = 800 600
}

# windowrule {
#    name = "PiP"
#    match:title = Picture-in-Picture
#    float = on
#    size = 480 270
#    move = 1100 30
#    pin = on
#}

windowrule {
    name = "TDE Application"
    match:class = tde.TDEApplication
    float = on
    center = on
}

layerrule = order 999, match:namespace notifyPanel
